DROP TABLE IF EXISTS users, items, booking, comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    owner_id BIGINT NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_items_users FOREIGN KEY (owner_id) REFERENCES users (id)
    );

CREATE TABLE IF NOT EXISTS booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY(id),
    CONSTRAINT check_status_booking CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED')),
    CONSTRAINT fk_booking_items FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_booking_users FOREIGN KEY (booker_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_text VARCHAR(1000) NOT NULL,
    item_id  BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY(id),
    CONSTRAINT fk_comments_items FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_comments_users FOREIGN KEY(author_id) REFERENCES users(id)
);